---
  targets:
    - target : "default"
      update_to : "latest"
    - target : "12"
      update_to : "13"
  cve_urgency_levels:
    - cve_urgency_conditions:
        max_baseScore : 20
      deadline_days: 2
      name: "critical"
    - cve_urgency_conditions:
        max_baseScore : 10
        average_baseScore : 8
        max_exploitabilityScore : 10
        average_exploitabilityScore : 8
        max_impactScore : 10
        average_impactScore : 8
        number_CVEs : 10
        number_actively_exploited_CVEs : 5
        fraction_actively_exploited_CVEs : 0.7
        formulas:
          - comparison : "average"
            formula : "baseScore * exploitabilityScore * impactScore"
            threshold : 500
          - comparison : "max"
            formula : "baseScore * exploitabilityScore * impactScore * is_actively_exploited"
            threshold : 200
          - comparison : "sum"
            formula    : "baseScore  * impactScore * is_actively_exploited"
            threshold : 300
          - comparison : "n_above"
            formula    : "baseScore  * impactScore * is_actively_exploited"
            n : 2
            threshold : 300
      deadline_days : 7  
      conjunction : false
  default_deadline_days : 14


